export type CuratedTrackSeed = {
  slug: string
  title: string
  description: string
  sortOrder: number
  problemTitles: string[]
}

const BLIND_75_TITLES = [
  "Two Sum",
  "Best Time to Buy and Sell Stock",
  "Contains Duplicate",
  "Product of Array Except Self",
  "Maximum Subarray",
  "Maximum Product Subarray",
  "Find Minimum in Rotated Sorted Array",
  "Search in Rotated Sorted Array",
  "3Sum",
  "Container With Most Water",
  "Merge Intervals",
  "Insert Interval",
  "Non-overlapping Intervals",
  "Reverse Linked List",
  "Merge Two Sorted Lists",
  "Linked List Cycle",
  "Reorder List",
  "Remove Nth Node From End of List",
  "Climbing Stairs",
  "Coin Change",
  "House Robber",
  "House Robber II",
  "Longest Palindromic Substring",
  "Palindromic Substrings",
  "Longest Common Subsequence",
  "Number of Islands",
  "Clone Graph",
  "Pacific Atlantic Water Flow",
  "Course Schedule",
  "Word Search",
  "Maximum Depth of Binary Tree",
  "Balanced Binary Tree",
  "Diameter of Binary Tree",
  "Binary Tree Level Order Traversal",
  "Invert Binary Tree",
  "Same Tree",
  "Subtree of Another Tree",
  "Validate Binary Search Tree",
  "Kth Smallest Element in a BST",
  "Binary Tree Right Side View",
  "Construct Binary Tree from Preorder and Inorder Traversal",
  "Implement Trie (Prefix Tree)",
] as const

const NEETCODE_150_EXTRA_TITLES = [
  "Valid Parentheses",
  "Min Stack",
  "Evaluate Reverse Polish Notation",
  "Generate Parentheses",
  "Daily Temperatures",
  "Top K Frequent Elements",
  "Kth Largest Element in an Array",
  "Binary Search",
  "Search a 2D Matrix",
  "Koko Eating Bananas",
  "Find Median from Data Stream",
  "Encode and Decode Strings",
  "Longest Consecutive Sequence",
  "Group Anagrams",
  "Longest Substring Without Repeating Characters",
  "Trapping Rain Water",
  "Subsets",
  "Subsets II",
  "Permutations",
  "Combination Sum",
  "Combination Sum II",
  "Word Break",
  "Decode Ways",
  "Jump Game",
  "Jump Game II",
  "Unique Paths",
  "Set Matrix Zeroes",
  "Spiral Matrix",
  "Rotate Image",
  "Add Two Numbers",
  "Merge k Sorted Lists",
  "Partition Equal Subset Sum",
  "Course Schedule II",
  "Redundant Connection",
  "Number of Connected Components in an Undirected Graph",
  "Alien Dictionary",
  "Word Ladder",
  "Lowest Common Ancestor of a Binary Tree",
  "Lowest Common Ancestor of a Binary Search Tree",
  "Serialize and Deserialize Binary Tree",
  "Count Good Nodes in Binary Tree",
  "Best Time to Buy and Sell Stock II",
  "Majority Element",
  "Subarray Sum Equals K",
  "Longest Increasing Subsequence",
  "Coin Change II",
  "Target Sum",
] as const

const NEETCODE_250_EXTRA_TITLES = [
  "Two Sum II - Input Array Is Sorted",
  "3Sum Closest",
  "4Sum",
  "Binary Tree Zigzag Level Order Traversal",
  "Flatten Binary Tree to Linked List",
  "Path Sum",
  "Path Sum II",
  "Binary Tree Maximum Path Sum",
  "Construct Binary Tree from Inorder and Postorder Traversal",
  "Maximum Binary Tree",
  "Construct Quad Tree",
  "Time Based Key-Value Store",
  "LRU Cache",
  "Design Add and Search Words Data Structure",
  "Word Search II",
  "Pacific Atlantic Water Flow",
  "Surrounded Regions",
  "Number of Islands II",
  "Graph Valid Tree",
  "Shortest Path in Binary Matrix",
  "Cheapest Flights Within K Stops",
  "Network Delay Time",
  "Critical Connections in a Network",
  "Find Minimum Time to Finish All Jobs",
  "Longest String Chain",
  "Maximum Length of Pair Chain",
  "Burst Balloons",
  "Perfect Squares",
  "Coin Change II",
  "Can Partition K Subsets",
  "Longest Repeating Character Replacement",
  "Minimum Window Substring",
  "Sliding Window Maximum",
] as const

const STRIVER_A_TO_Z_TITLES = [
  "Pascal's Triangle",
  "Next Permutation",
  "Set Matrix Zeroes",
  "Rotate Image",
  "Spiral Matrix",
  "Subarray Sum Equals K",
  "Majority Element",
  "Majority Element II",
  "Best Time to Buy and Sell Stock",
  "Best Time to Buy and Sell Stock II",
  "Two Sum",
  "Two Sum II - Input Array Is Sorted",
  "3Sum",
  "4Sum",
  "Longest Consecutive Sequence",
  "Maximum Subarray",
  "Maximum Product Subarray",
  "Product of Array Except Self",
  "Merge Intervals",
  "Insert Interval",
  "Non-overlapping Intervals",
  "Merge Two Sorted Lists",
  "Reverse Linked List",
  "Linked List Cycle",
  "Remove Nth Node From End of List",
  "Add Two Numbers",
  "Find the Duplicate Number",
  "Search in Rotated Sorted Array",
  "Find Minimum in Rotated Sorted Array",
  "Koko Eating Bananas",
  "Trapping Rain Water",
  "House Robber",
  "House Robber II",
  "Longest Palindromic Substring",
  "Longest Common Subsequence",
  "Longest Increasing Subsequence",
  "Partition Equal Subset Sum",
  "Decode Ways",
  "Unique Paths",
  "Number of Islands",
  "Flood Fill",
  "Rotting Oranges",
  "Clone Graph",
  "Course Schedule",
  "Course Schedule II",
  "Word Search",
  "Word Ladder",
  "Binary Tree Level Order Traversal",
  "Binary Tree Right Side View",
  "Balanced Binary Tree",
  "Diameter of Binary Tree",
  "Maximum Depth of Binary Tree",
  "Validate Binary Search Tree",
] as const

const SDE_SHEET_TITLES = [
  "Two Sum",
  "Best Time to Buy and Sell Stock",
  "Contains Duplicate",
  "Maximum Subarray",
  "Maximum Product Subarray",
  "Product of Array Except Self",
  "Find Minimum in Rotated Sorted Array",
  "Search in Rotated Sorted Array",
  "3Sum",
  "Merge Intervals",
  "Insert Interval",
  "Merge Two Sorted Lists",
  "Reverse Linked List",
  "Remove Nth Node From End of List",
  "Linked List Cycle",
  "Climbing Stairs",
  "Coin Change",
  "House Robber",
  "Number of Islands",
  "Clone Graph",
  "Course Schedule",
  "Word Search",
  "Binary Tree Level Order Traversal",
  "Maximum Depth of Binary Tree",
  "Balanced Binary Tree",
  "Diameter of Binary Tree",
  "Validate Binary Search Tree",
  "Kth Smallest Element in a BST",
  "Binary Tree Right Side View",
  "Longest Common Subsequence",
  "Longest Increasing Subsequence",
  "Partition Equal Subset Sum",
  "Subarray Sum Equals K",
  "Majority Element",
  "Set Matrix Zeroes",
  "Rotate Image",
  "Spiral Matrix",
  "Pascal's Triangle",
  "Next Permutation",
  "Longest Consecutive Sequence",
  "Search a 2D Matrix",
  "Top K Frequent Elements",
  "Kth Largest Element in an Array",
  "Trapping Rain Water",
  "Decode Ways",
  "Unique Paths",
  "Word Break",
] as const

export const CURATED_TRACKS: CuratedTrackSeed[] = [
  {
    slug: "blind-75",
    title: "Blind 75",
    description: "The highest-signal starter list for interview prep.",
    sortOrder: 0,
    problemTitles: [...BLIND_75_TITLES],
  },
  {
    slug: "neetcode-150",
    title: "NeetCode 150",
    description: "A broader practice path that expands on Blind 75.",
    sortOrder: 1,
    problemTitles: [...BLIND_75_TITLES, ...NEETCODE_150_EXTRA_TITLES],
  },
  {
    slug: "neetcode-250",
    title: "NeetCode 250",
    description: "A deeper interview set that covers more patterns and edge cases.",
    sortOrder: 2,
    problemTitles: [...BLIND_75_TITLES, ...NEETCODE_150_EXTRA_TITLES, ...NEETCODE_250_EXTRA_TITLES],
  },
  {
    slug: "striver-a-to-z",
    title: "Striver A to Z",
    description: "A structured problem path that moves from basics to advanced patterns.",
    sortOrder: 3,
    problemTitles: [...STRIVER_A_TO_Z_TITLES],
  },
  {
    slug: "sde-sheet",
    title: "SDE Sheet",
    description: "A compact revision sheet built around high-frequency interview problems.",
    sortOrder: 4,
    problemTitles: [...SDE_SHEET_TITLES],
  },
]

export function normalizeProblemTitle(title: string) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
}
